# Generated by Django 5.0.1 on 2024-01-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_directors_director_rename_films_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='birth_year',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='film',
            name='rel_year',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
